function uw(){var el=$('wi'),s=$('ws');if(!el||!s)return;sf('wc',wm.length);el.textContent=wm.length?wm.length+' watermark(s)':'No watermarks';var wmf=$('wmf');var ft=wmf?wmf.value:'';var filtered=ft?wm.filter(function(w){return w.ty===ft}):wm;s.innerHTML='<option value=-1>--</option>';filtered.forEach(function(w){var o=document.createElement('option');o.value=w.id;o.textContent='['+w.ty+'] #'+w.id+' '+w.txt.substring(0,10);s.appendChild(o)});if(sel>=0)s.value=sel}
function wmUp(){if(sel<0||wm.length<2)return;var idx=-1;for(var i=0;i<wm.length;i++){if(wm[i].id===sel){idx=i;break}}if(idx<=0)return;var t=wm[idx];wm[idx]=wm[idx-1];wm[idx-1]=t;uw();lg('reorder: #'+wm[idx-1].id+' up')}
function wmDown(){if(sel<0||wm.length<2)return;var idx=-1;for(var i=0;i<wm.length;i++){if(wm[i].id===sel){idx=i;break}}if(idx<0||idx>=wm.length-1)return;var t=wm[idx];wm[idx]=wm[idx+1];wm[idx+1]=t;uw();lg('reorder: #'+wm[idx+1].id+' down')}

function ws(){var s=$('ws');if(!s)return;var id=parseInt(s.value);sel=id;if(id<0){rw();return}var w=null;for(var i=0;i<wm.length;i++){if(wm[i].id===id){w=wm[i];break}}if(!w)return;var wet=$('wet');if(wet)wet.value=w.txt;$('rx').value=w.px;sf('vx',w.px+'%');$('ry').value=w.py;sf('vy',w.py+'%');$('rr').value=w.rt;sf('vr',w.rt);$('rs').value=w.fs;sf('vs',w.fs);$('ro').value=w.op;sf('vo',w.op+'%');rw()}

function wd(){var s=$('ws');if(!s||s.value<0)return;var id=parseInt(s.value);wm=wm.filter(function(w){return w.id!==id});s.value=-1;sel=-1;uw();cc();rw();lg('-WM #'+id)}

function applyFilter(){uw();var s=$('ws');if(s){var inList=false;for(var i=0;i<s.options.length;i++){if(s.options[i].value==sel)inList=true}if(!inList){sel=-1;var e=$('wet');if(e)e.value=''}}}

function updateTypeDesc(){var el=$('typeDesc');var amt=$('amt');var pwd=$('apwd');if(el&&amt){el.textContent=typeHints[amt.value]||'';var hint=el.textContent;if(!encryptOk[amt.value]){hint+=' [NO ENCRYPTION - too small]'}el.textContent=hint}if(pwd&&amt){if(!encryptOk[amt.value]){pwd.disabled=true;pwd.placeholder='Encryption not available for this type'}else{pwd.disabled=false;pwd.placeholder='Password (optional)'}}}
function openAddDlg(){_editId=-1;var btn=$('addBtn');if(btn)btn.textContent='+ ADD TO LIST';var m=$('wmModal');if(m)m.style.display='flex';$('atext').value='';$('atext').focus();renderDlgList();updateTypeDesc()}
function closeAddDlg(){var m=$('wmModal');if(m)m.style.display='none';uw();rw()}

function renderDlgList(){var el=$('adlgList');var cnt=$('adlgCount');if(cnt)cnt.textContent=wm.length;if(!el)return;el.innerHTML='';wm.forEach(function(w){var d=document.createElement('div');d.style.cssText='padding:3px 2px;border-bottom:1px solid var(--hairline);font-size:10px;color:var(--ink);cursor:pointer';var label='['+w.ty+'] '+w.txt.substring(0,35);if(w.pwd)label+=' [LOCKED]';d.textContent=label;d.onclick=function(){_editId=w.id;$('amt').value=w.ty;updateTypeDesc();$('atext').value=w.txt;$('apwd').value=w.pwd||'';$('atext').focus();var btn=$('addBtn');if(btn)btn.textContent='UPDATE #'+w.id};el.appendChild(d)});var e=$('wc');if(e)e.textContent=wm.length}
function addFromDlg(){var tp=$('amt').value;var pwd=$('apwd').value||'';var txt=$('atext').value.trim();if(!txt)return;if(_editId>=0){var eid=_editId;wm.forEach(function(w){if(w.id===eid){w.ty=tp;w.txt=txt;w.pwd=pwd}});_editId=-1;var btn=$('addBtn');if(btn)btn.textContent='+ ADD TO LIST';lg('updated #'+eid);renderDlgList();uw();rw();cc();return}var id=++wid;var o={id:id,ty:tp,txt:txt,pwd:pwd,px:(id*7+13)%60,py:(id*9+15)%60,rt:0,fs:36,op:85};if(tp==='freq'){o.alpha=st.al;o.delta=st.de;o.level=st.lv;o.sync=!!st.sy;o.bch=!!st.bc}if(tp==='dft'){o.strength=50}if(tp==='dct_block'){o.strength=30}if(tp==='svd'){o.strength=40}if(tp==='spread'){o.strength=30;o.spread_factor=64;o.seed=42}if(tp==='patchwork'){o.strength=25;o.seed=7}if(tp==='visible'){o.opacity=85/100;o.x=50;o.y=50;o.font_size=48;o.rotation=0}wm.push(o);$('atext').value='';$('apwd').value='';$('atext').focus();renderDlgList();uw();var el=$('ws');if(el)el.value=id;sel=id;rw();cc();lg('+1 ['+tp+']')}

function clearAll(){wm=[];wid=0;sel=-1;uw();cc();rw();var wt=$('wet');if(wt)wt.value='';lg('all cleared')}

function exportCfg(){if(!wm.length){lg('nothing to export','e');return}var cfg={version:1,watermarks:wm.map(function(w){var o={type:w.ty,text:w.txt};if(w.pwd)o.password=w.pwd;for(var k in w){if(k==='id'||k==='ty'||k==='txt'||k==='pwd')continue;if(k==='px'||k==='py'||k==='rt'||k==='fs'||k==='op')continue;o[k]=w[k]}return o})};var blob=new Blob([JSON.stringify(cfg,null,2)],{type:'application/json'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='watermarks.json';a.click();lg('exported')}
function importCfg(){$('cfgFile').click()}
function loadCfg(el){if(!el||!el.files||!el.files[0])return;var r=new FileReader();r.onload=function(e){try{var cfg=JSON.parse(e.target.result);if(!cfg.watermarks||!cfg.watermarks.length){lg('invalid','e');return}wm=[];wid=0;cfg.watermarks.forEach(function(w){var id=++wid;var o={id:id,ty:w.type||'freq',txt:w.text||'',px:(id*7+13)%60,py:(id*9+15)%60,rt:0,fs:36,op:85};if(w.password)o.pwd=w.password;if(w.alpha!==undefined){o.alpha=w.alpha;st.al=w.alpha;sf('va',st.al.toFixed(2));var ra=$('ra');if(ra)ra.value=w.alpha*100}if(w.delta!==undefined){o.delta=w.delta;st.de=w.delta;sf('vd',w.delta);var rd=$('rd');if(rd)rd.value=w.delta}if(w.level!==undefined){o.level=w.level;st.lv=w.level;sf('vl',w.level);var rl=$('rl');if(rl)rl.value=w.level}if(w.sync!==undefined){o.sync=w.sync;st.sy=w.sync;var ts=$('ts');if(ts){ts.textContent=w.sync?'ON':'OFF';ts.classList.toggle('a',w.sync)}}if(w.bch!==undefined){o.bch=w.bch;st.bc=w.bch;var tb=$('tb');if(tb){tb.textContent=w.bch?'ON':'OFF';tb.classList.toggle('a',w.bch)}}if(w.strength!==undefined)o.strength=w.strength;if(w.seed!==undefined)o.seed=w.seed;if(w.spread_factor!==undefined)o.spread_factor=w.spread_factor;if(w.x!==undefined)o.px=w.x;if(w.y!==undefined)o.py=w.y;if(w.font_size!==undefined)o.fs=w.font_size;if(w.rotation!==undefined)o.rt=w.rotation;if(w.opacity!==undefined)o.op=Math.round(w.opacity*100);wm.push(o)});sel=-1;uw();cc();rw();lg('imported '+wm.length)}catch(err){lg('bad JSON','e')}};r.readAsText(el.files[0]);el.value=''}

var _ccTimer=null;function cc(){if(_ccTimer)clearTimeout(_ccTimer);_ccTimer=setTimeout(function(){_ccTimer=null;if(!st.cd){var e=$('cpd');if(e)e.textContent='MAX: -- bytes';return}var w=st.cd.w||256,h=st.cd.h||256;var txt='';if(wm.length){txt=wm.map(function(w){return w.txt}).join('|')}else{var wet=$('wet');txt=wet?wet.value:''}var used=txt.length;var e=$('cpd');if(e)e.textContent='...';fetch('http://127.0.0.1:8080/api/capacity?width='+w+'&height='+h+'&level='+st.lv+'&sync_enabled='+(st.sy?1:0)+'&bch_enabled='+(st.bc?1:0)).then(function(r){if(!r.ok)throw Error();return r.json()}).then(function(d){var m=d.max_bytes||0;var e=$('cpd');if(e){e.textContent='MAX: '+m+' bytes | USED: '+used+' bytes';e.style.color=used>m?'var(--error)':'var(--muted)'}}).catch(function(){var e=$('cpd');if(e){e.textContent=used+' bytes';e.style.color='var(--muted)'}})},300)}

$('be').onclick=function(){if(st.bs)return;if(!st.cd){lg(tk('nc'),'e');return}st.bs=1;this.disabled=1;sf('mst',tk('bu'));$('mst').style.color='var(--error)';$('sd').className='dot r';var self=this;(st.m?dx():de()).then(function(){_reset()}).catch(function(e){lg(tk('er')+': '+e.message,'e');sf('mst','ERROR');$('mst').style.color='var(--error)';$('sd').className='dot r';st.bs=0;self.disabled=0})}

async function de(){if(!st.cd||!st.cd.f){lg('no image','e');return}var on=st.cd.f&&st.cd.f.name?st.cd.f.name.replace(/\.[^.]+$/,''):'watermarked';var n=new Date();var ts=''+n.getFullYear()+(n.getMonth()+1)+n.getDate()+n.getHours()+n.getMinutes();var fn=on+'-S-ANCHOR-'+ts+'.png';var di=document.getElementById('dlname');if(di)di.value=fn;var txt='';if(wm.length){txt=wm.map(function(w){return w.txt}).join('|');}else{var wet=$('wet');txt=wet?wet.value:''}lg(tk('eml')+' "'+txt.substring(0,40)+'..."');var b64=await d2b(st.cd.du);if(!txt){if(!wm.length){throw new Error('add a watermark first (click + ADD or type in the edit field below)')}txt=wm.map(function(w){return w.txt}).join('|')}var wm_specs=wm.length?wm.map(function(w){var p={type:w.ty,text:w.txt};if(w.pwd)p.password=w.pwd;if(w.alpha!==undefined)p.alpha=w.alpha;if(w.delta!==undefined)p.delta=w.delta;if(w.level!==undefined)p.level=w.level;if(w.sync!==undefined)p.sync=w.sync;if(w.bch!==undefined)p.bch=w.bch;if(w.strength!==undefined)p.strength=w.strength;if(w.spread_factor!==undefined)p.spread_factor=w.spread_factor;if(w.seed!==undefined)p.seed=w.seed;if(w.opacity!==undefined)p.opacity=w.opacity;if(w.x!==undefined)p.x=w.x;if(w.y!==undefined)p.y=w.y;if(w.font_size!==undefined)p.font_size=w.font_size;if(w.rotation!==undefined)p.rotation=w.rotation;if(w.ty==='freq'&&w.alpha===undefined){p.alpha=st.al;p.delta=st.de;p.level=st.lv;p.sync=!!st.sy;p.bch=!!st.bc}if(w.ty==='visible'&&w.x===undefined){p.opacity=w.op/100;p.x=w.px;p.y=w.py;p.font_size=w.fs;p.rotation=w.rt}return p}):[{type:'freq',text:txt,alpha:st.al,delta:st.de,level:st.lv,sync:!!st.sy,bch:!!st.bc}];var r=await fetch('http://127.0.0.1:8080/api/embed',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_b64:b64,watermarks:wm_specs})});if(!r.ok){try{var e=await r.json();throw new Error(e.error||'HTTP '+r.status)}catch(_){throw new Error('server error '+r.status)}}var d=await r.json();st.rd=d;if(d.results){d.results.forEach(function(r){lg('['+r.type+'] embedded','o')})}$('cw').src='data:image/png;base64,'+d.image_b64;$('cw').style.display='';$('cdi').style.display='';$('cdh').style.display='';$('cw').style.setProperty('--s','50%');$('cdi').style.left='50%';$('cdh').style.left='50%';var fr=d.results&&d.results.filter(function(r){return r.psnr!=null})[0]||{};sf('mp',(fr.psnr||'--')+' dB');sf('ms',fr.ssim||'--');sf('mb',fr.bits_embedded||'--');$('dlb').style.display='inline-block';$('dlb').dataset.b64=d.image_b64;var di=document.getElementById('dlname');if(di)di.style.display='';lg(tk('dn')+' PSNR='+(fr.psnr||'--')+'dB','o')}

async function dx(){var b64=await d2b(st.cd.du);var extPwd=$('expwd')?$('expwd').value:'';var seen={};var wm_specs=wm.length?wm.filter(function(w){if(seen[w.ty])return false;seen[w.ty]=true;return true}).map(function(w){var p={type:w.ty};var wp=w.pwd||extPwd;if(wp)p.password=wp;for(var k in w){if(k==='id'||k==='ty'||k==='txt'||k==='pwd')continue;if(k==='px'||k==='py'||k==='rt'||k==='fs'||k==='op')continue;p[k]=w[k]}if(w.ty==='freq'&&w.alpha===undefined){p.delta=st.de;p.level=st.lv;p.sync=!!st.sy;p.bch=!!st.bc}return p}):[{type:'freq',delta:st.de,level:st.lv,sync:!!st.sy,bch:!!st.bc}];if(extPwd&&!wm.length){wm_specs[0].password=extPwd}var r=await fetch('http://127.0.0.1:8080/api/extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_b64:b64,watermarks:wm_specs})});if(!r.ok){try{var e=await r.json();throw new Error(e.error||'HTTP '+r.status)}catch(_){throw new Error('server error')}}var d=await r.json();var parts=(d.results&&d.results.length)?d.results.map(function(r){var txt=r.text||'';var ok=txt.length>0&&txt!=='\x00';if(txt.indexOf('__visible_on_image__')>=0){ok=true;txt='[visible on image]'}if(r.needs_password){ok=true;txt='[NEEDS PASSWORD]'}if(r.decrypt_error){txt='[WRONG PASSWORD]'}return{type:r.type,text:txt.substring(0,55),ok:ok}}):[];var nFound=0;parts.forEach(function(p){if(p.ok){nFound++;lg('['+p.type+'] '+p.text,'o')}});lg('Found '+nFound+'/'+parts.length+' types');var xl=$('xl');if(xl){var found=parts.filter(function(p){return p.ok});xl.innerHTML='<div style="font-size:10px;font-weight:500;color:var(--muted);padding:4px 0;border-bottom:1px solid var(--hairline);letter-spacing:.5px">FOUND '+found.length+'/'+parts.length+'</div>';found.forEach(function(p){var d2=document.createElement('div');d2.style.cssText='display:flex;align-items:baseline;gap:6px;border-bottom:1px solid var(--hairline);padding:5px 4px';var n=document.createElement('span');n.style.cssText='color:var(--primary);font-size:10px;font-weight:500;text-transform:uppercase;letter-spacing:.3px;white-space:nowrap';n.textContent='['+p.type+']';d2.appendChild(n);var t=document.createElement('span');t.style.cssText='color:var(--body);font-size:12px;word-break:break-all;line-height:1.4';t.textContent=p.text;d2.appendChild(t);xl.appendChild(d2)})}showExtract(parts)}
var rs=$('results');if(rs&&$('xl')){rs.innerHTML=$('xl').innerHTML}

async function d2b(u){var r=await fetch(u),b=await r.blob();return new Promise(function(r){var f=new FileReader();f.onloadend=function(){r(f.result.split(',')[1])};f.readAsDataURL(b)})}
function dl(){var b=$('dlb').dataset.b64;if(!b)return;var fn=document.getElementById('dlname');var name=fn&&fn.value?fn.value:'s-anchor.png';var a=document.createElement('a');a.href='data:image/png;base64,'+b;a.download=name;document.body.appendChild(a);a.click();document.body.removeChild(a);lg(tk('sc'))}

function showExtract(parts){var cv=$('cv');cv.style.display='block';$('pn').style.display='none';cv.width=cv.offsetWidth;cv.height=cv.offsetHeight;if(!cv.width||!cv.height)return;var ctx=cv.getContext('2d');if(st.cd&&st.cd.el){var s=Math.min(cv.width/st.cd.w,cv.height/st.cd.h);var ox=(cv.width-st.cd.w*s)/2,oy=(cv.height-st.cd.h*s)/2;ctx.drawImage(st.cd.el,ox,oy,st.cd.w*s,st.cd.h*s)}var bh=28+16*parts.length;ctx.fillStyle='rgba(24,23,21,0.85)';ctx.fillRect(0,cv.height-bh,cv.width,bh);ctx.fillStyle='#cc785c';ctx.font='bold 11px Inter,sans-serif';ctx.textAlign='left';ctx.textBaseline='top';var nFound=parts.filter(function(p){return p.ok}).length;ctx.fillText('FOUND '+nFound+'/'+parts.length,10,cv.height-bh+6);ctx.fillStyle='#faf9f5';ctx.font='11px JetBrains Mono,monospace';var fi=0;parts.forEach(function(p,i){if(!p.ok)return;ctx.fillStyle='#cc785c';ctx.font='bold 10px Inter,sans-serif';ctx.fillText('['+p.type+']',10,cv.height-bh+22+14*fi);ctx.fillStyle='#faf9f5';var tw=ctx.measureText('['+p.type+']').width;ctx.font='11px JetBrains Mono,monospace';ctx.fillText(p.text,14+tw,cv.height-bh+22+14*fi);fi++})}

document.getElementById('be2').onclick=function(){if(st.bs)return;if(!st.cd){lg(tk('nc'),'e');return}st.bs=1;this.disabled=1;sf('mst',tk('bu'));$('mst').style.color='var(--error)';$('sd').className='dot r';var self=this;dx().then(function(){$('sd').className='dot g';sf('mst',tk('id'));$('mst').style.color='var(--success)';st.bs=0;self.disabled=0}).catch(function(e){lg(tk('er')+': '+e.message,'e');sf('mst','ERROR');$('mst').style.color='var(--error)';$('sd').className='dot r';st.bs=0;self.disabled=0})}
$('pd').textContent='0x'+Math.floor(Math.random()*0xFFFF).toString(16).toUpperCase()
var _wt=$('wt');if(_wt)_wt.oninput=function(){var v=this.value;if(sel>=0){wm.forEach(function(w){if(w.id===sel)w.txt=v})}rw();cc()}
lg(tk('in'));lg(tk('wa'))